/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f36bd3fb41ac995e1af816661f19f89e)
interface __BaseEnv_Env {
	SUPABASE_URL: "";
	SUPABASE_PUBLISHABLE_KEY: "";
	COMPUTE_URL: "";
	APP_ORIGIN: "";
	SUPABASE_SECRET_KEY: string;
	ENGINEERING_COMPUTE_TOKEN: string;
	ENGINEERING_VALIDATION: Workflow<Parameters<import("./src/index").EngineeringValidation['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "COMPUTE_URL" | "APP_ORIGIN" | "SUPABASE_SECRET_KEY" | "ENGINEERING_COMPUTE_TOKEN">> {}
}
