/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: adcc24b88f5a90b626dccfc7fafecd0e)
interface __BaseEnv_Env {
	SUPABASE_URL: "";
	SUPABASE_PUBLISHABLE_KEY: "";
	ENGINEERING_APP_ORIGIN: "";
	CLOUDFLARE_DISPATCH_URL: "";
	SUPABASE_STORAGE_BUCKET: "engineering-private";
	PYTHON_BACKEND_URL: "";
	SUPABASE_DB_URL: string;
	SUPABASE_SECRET_KEY: string;
	ENGINEERING_SERVICE_TOKEN: string;
	DEEPSEEK_API_KEY: string;
	ENGINEERING_RUNTIME: DurableObjectNamespace<import("./src/index").EngineeringRuntime>;
	ENGINEERING_TASKS: Workflow<Parameters<import("./src/index").EngineeringTask['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "EngineeringRuntime";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "ENGINEERING_APP_ORIGIN" | "CLOUDFLARE_DISPATCH_URL" | "SUPABASE_STORAGE_BUCKET" | "PYTHON_BACKEND_URL" | "SUPABASE_DB_URL" | "SUPABASE_SECRET_KEY" | "ENGINEERING_SERVICE_TOKEN" | "DEEPSEEK_API_KEY">> {}
}
